allowBuilds:
  '@apollo/protobufjs': true
  '@sveltejs/kit': true
  core-js: true
  esbuild: true
  houdini-core: true
  houdini-svelte: true
  sharp: true
  svelte-preprocess: true
  workerd: true
minimumReleaseAgeExclude:
  - houdini@2.0.0-next.35
