allowBuilds:
  core-js: true
  houdini-core: true
  houdini-react: true
minimumReleaseAgeExclude:
  - houdini-react-darwin-arm64@2.0.0-next.32
  - houdini-react-darwin-x64@2.0.0-next.32
  - houdini-react-linux-arm64@2.0.0-next.32
  - houdini-react-linux-x64@2.0.0-next.32
  - houdini-react@2.0.0-next.32
  - houdini@2.0.0-next.30
